controller_manager:
  ros__parameters:
    update_rate: 500  # Control loop frequency in Hz
    
    # Controller list
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    velocity_controller:
      type: pid_controller/PidController

# Joint state broadcaster - publishes all joint states
joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interfaces:
      - position
      - velocity
      - effort

# PID controller for velocity control on both joints (pan and tilt axis)
velocity_controller:
  ros__parameters:
    # 控制的关节名称
    dof_names:
      - joint1
      - joint2
    
    # 参考和状态接口类型（velocity - 速度控制）
    reference_and_state_interfaces:
      - velocity
    
    # 命令接口类型（effort - 输出力矩到硬件）
    command_interface: effort
    
    # 使用外部测量状态（从硬件读取）
    use_external_measured_states: false
    
    # PID参数配置 - 每个关节单独配置
    gains:
      joint1:  # Pan axis (joint1)
        p: 0.7              # 比例增益
        i: 0.0              # 积分增益  
        d: 0.0              # 微分增益
        i_clamp_max: 5.0    # 积分上限
        i_clamp_min: -5.0   # 积分下限
        feedforward_gain: 0.0  # 前馈增益
        
      joint2:  # Tilt axis (joint2)
        p: 0.7              # 比例增益
        i: 0.0              # 积分增益
        d: 0.0              # 微分增益
        i_clamp_max: 3.0    # 积分上限
        i_clamp_min: -3.0   # 积分下限
        feedforward_gain: 0.0  # 前馈增益 